### ISSUE TITLE
How can the reflectance of a 3D object be turned off during visualization in the rend_point.py script?

### ISSUE THREAD

**Issue by vovantuan1999a** [yyvhang/IAGNet#2]
Dear Sir,

I would like to express my gratitude for your intriguing research.

Your code is truly remarkable and has been of immense assistance to me.

Could you kindly guide me on how to deactivate the reflectance of a 3D object in the rend_point.py script during visualization?

Thank you sincerely and best regards.

**Comment by yyvhang** [comment]
> Dear Sir,
> 
> I would like to express my gratitude for your intriguing research.
> 
> Your code is truly remarkable and has been of immense assistance to me.
> 
> Could you kindly guide me on how to deactivate the reflectance of a 3D object in the rend_point.py script during visualization?
> 
> Thank you sincerely and best regards.

**Comment by yyvhang** [comment]
> Dear Sir,
> 
> I would like to express my gratitude for your intriguing research.
> 
> Your code is truly remarkable and has been of immense assistance to me.
> 
> Could you kindly guide me on how to deactivate the reflectance of a 3D object in the rend_point.py script during visualization?
> 
> Thank you sincerely and best regards.

Hi, thanks for your interest！
This code uses the rendering engine Mitsuba for rendering, so if you want to remove reflections, I suggest you directly use the rendering engine and cancel the lighting. Import the .ply file of the inference result into Blender and use 'mesh to points' to convert it into a point cloud. Then, add the material to see the color information of the inference result. 
Hope this helps, best!

**Comment by vovantuan1999a** [comment]
Thank you very much for your response.
It has been incredibly helpful to me.
