### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by RayYoh** [yyvhang/IAGNet#3]
Dear Authors,

Thanks for your great work.
Is there any plan to release the dataset?

Best

**Comment by yyvhang** [comment]
> Dear Authors,
> 
> Thanks for your great work. Is there any plan to release the dataset?
> 
> Best

Hi, thanks for your interest. I'm just finish the iccv conference, the dataset will be released very soon, before the ddl of CVPR2024.

**Comment by RayYoh** [comment]
> > Dear Authors,
> > Thanks for your great work. Is there any plan to release the dataset?
> > Best
> 
> Hi, thanks for your interest. I'm just finish the iccv conference, the dataset will be released very soon, before the ddl of CVPR2024.

Thx.

**Comment by EAST-J** [comment]
Hi, any updates about the dataset?

> > Dear Authors,
> > Thanks for your great work. Is there any plan to release the dataset?
> > Best
> 
> Hi, thanks for your interest. I'm just finish the iccv conference, the dataset will be released very soon, before the ddl of CVPR2024.

**Comment by yyvhang** [comment]
> Hi, any updates about the dataset?
> 
> > > Dear Authors,
> > > Thanks for your great work. Is there any plan to release the dataset?
> > > Best
> > 
> > 
> > Hi, thanks for your interest. I'm just finish the iccv conference, the dataset will be released very soon, before the ddl of CVPR2024.

The dataset has been released. Thanks for your interest!
