### ISSUE TITLE
resume Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by mxmdpc** [yyvhang/IAGNet#4]
Hi!
Thank you for your work that has contributed so much. I always encounter this problem when I repeat. When I resume, the problem "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" appears. How can I solve it?

With best wishes!

**Comment by yyvhang** [comment]
> Hi! Thank you for your work that has contributed so much. I always encounter this problem when I repeat. When I resume, the problem "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!" appears. How can I solve it?
> 
> With best wishes!

Could you please provide more details about this error, e.g. which script arises this error.

**Comment by mxmdpc** [comment]
Thank you for your reply. The error occurred in train.py. I used the ‘-- resume’ command to load the trained best_seen.pt model without modifying any code, resulting in an error of "Expected all tensors to be on the same device, but found at least two devices, cuda: 0 and CPU!".

**Comment by yyvhang** [comment]
> Thank you for your reply. The error occurred in train.py. I used the ‘-- resume’ command to load the trained best_seen.pt model without modifying any code, resulting in an error of "Expected all tensors to be on the same device, but found at least two devices, cuda: 0 and CPU!".

If using --resume, you should put line83 "model = model.to(device)" before loading model parameters (.pt).

**Comment by mxmdpc** [comment]
Thanks, it worked!
