### ISSUE TITLE
could you offer the code of getting the" B = {Bsub, Bobj }"?

### ISSUE THREAD

**Issue by JohnSnow-QY** [yyvhang/IAGNet#6]

**Comment by yyvhang** [comment]
> _No description provided._

Please refer to the functions "get_crop"、"random_crop_with_points"、"get_resize_box" in [dataset_PIAD.py](https://github.com/yyvhang/IAGNet/blob/master/data_utils/dataset_PIAD.py)

**Comment by JohnSnow-QY** [comment]
sorry ,I can't  express clearly , what I want is how generate the 'Json file" that include the "Box" parameters.
It  includ B={Bsub,Bobj}, how can I generate it ?
thank you for response

**Comment by yyvhang** [comment]
> sorry ,I can't express clearly , what I want is how generate the 'Json file" that include the "Box" parameters. It includ B={Bsub,Bobj}, how can I generate it ? thank you for response

Please use the "Labelme" software to annotate the box and just store the annotated box in JSON format, here is an [example](https://www.geeksforgeeks.org/reading-and-writing-json-to-a-file-in-python/) to save JSON file, you could refer to it.

**Comment by JohnSnow-QY** [comment]
thanks for response , very helpful
